---
title: "chapter4.Rmd"
output: html_document
---
# Week 4: Ville Turppo 15.11.2020

# Installing the MASS package, opening libraries and then loading the data.
library(MASS)
library(ggplot2)
library(dplyr)
data("Boston")

# 2) Exploring the data: There are 506 observations and 14 variables. Variablenames also shown below. Summary shows: mean,median,25th and 75th quartiles,min,max.

dim(Boston)
str(Boston)
variable.names(Boston)

#Graphical and summary summary: mean,median,25th and 75th quartiles,min,max.
summary(Boston)
pairs(Boston)
# It seems that e.g. crimrerate is higher when people live in older houses, when pupil-teacher ratio is bigger and when the houses are cheaper.

# 3) Corrplot library for the next plots of graphical view.

library(corrplot)
cor_matrix<-cor(Boston) %>% round(digits = 2)
cor_matrix
corrplot(cor_matrix, method="circle", type="upper", cl.pos="b", tl.pos="d", tl.cex = 0.6)

#The correlation plot shows the correlations between variables. The bigger circles the more correlation. Blue color for positive and Red for negative correlation.

# 4) scaling the data: Standardizing variables and the summary. Plus Changing the object to dataframe.

boston_scaled <- scale(Boston)
summary(boston_scaled)
boston_scaled <- as.data.frame(boston_scaled)

# Now all means = 0 and the values are "closer" each other. E.g. before "age" max was 100.00 and now it is 1.11. Compared to "dis" max 12.1 and 3.96. The variables are now better compareable.
library(tidyr)

# Categorical variable of the crime rate. And removing the old crim variable.
summary(boston_scaled$crim)

# Breakpoints for the new crim and making new "crime" variable and naming the categories.
bins <- quantile(boston_scaled$crim)
crime <- cut(boston_scaled$crim, breaks = bins, include.lowest = TRUE, labels = c("low", "med_low", "med_high", "high"))

# Removing "crim" and Adding the "crime" to the data
boston_scaled <- dplyr::select(boston_scaled, -crim)
boston_scaled <- data.frame(boston_scaled, crime)

# Finally dividing the data to test and train sets
n <- nrow(boston_scaled)
ind <- sample(n,  size = n * 0.8)
train <- boston_scaled[ind,]
test <- boston_scaled[-ind,]
correct_classes <- test$crime
test <- dplyr::select(test, -crime)

# 5) Discriminant analysis on the train set







```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
